# feign 相关配置
feign:
  client:
    config:
      # default 全局配置
      default:
        # 日志级别
        loggerLevel: BASIC
  # 连接池优化
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50